services:
  helper-api:
    image: registry.cn-shenzhen.aliyuncs.com/janeyre/cloakbrowser-helper
    restart: always
    ports:
      - 3000:3000

  frpc:
    #image: fatedier/frpc:v0.69.1
    image: registry.cn-shenzhen.aliyuncs.com/janeyre/frpc:v0.69.1
    restart: always
    command: ["-c", "/etc/frp/frpc.toml"]
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml
    depends_on:
      - helper-api
